# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ToDoNative' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ToDoNative
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTWebSocket',
    'RCTImage',
    'RCTAnimation',
    'ART',
    'RCTActionSheet',
    'RCTGeolocation',
    'RCTNetwork',
    'RCTSettings',
    'RCTVibration',
    'DevSupport',
    'BatchedBridge’,
    ‘RCTPushNotification’,
    'RCTLinkingIOS',
  ]
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk/ios'

  target 'ToDoNativeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ToDoNative-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ToDoNative-tvOS

  target 'ToDoNative-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
