# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ToDoNative' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ToDoNative
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  # pod 'FBSDKCoreKit'
  # pod 'FBSDKLoginKit'



  pod 'React', :path => '../node_modules/react-native'

  target 'ToDoNativeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
